[project]
name = "creativerank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.8",
    "mlflow>=3.5.1",
    "pandas>=2.3.3",
]
